// Generated by https://quicktype.io

import data from "./actors.json";

export const getPosts = () => data.actors; // alle poster

export const getById = (id) => {

  console.log(id);

    return data.actors.find((post) => post.id === id)

}